import { Career } from '../types';

export const MY_CAREERS: Career[] = [
  {
    logoUrl: '/svgs/ins.webp',
    role: 'Full Stack Developer',
    companyLabel: 'Insignia ID',
    companyFullName: 'Insignia ID',
    address: 'Jakarta, Indonesia 🇮🇩',
    fromDate: new Date('2021-08-01'),
    endDate: new Date('2021-12-01'),
    workMode: 'Part-time',
    workType: 'Remote',
    responsibilities: [
      'Designed an efficient and sustainable dashboard template by utilizing Laravel and Vue JS.',
      'Developed ETL (Extract, Transform, Load) tools that feature drag-and-drop functionality.',
      'Built a website for online travel and tour booking that offers a range of services.',
    ],
  },
  {
    logoUrl: '/svgs/umpo.png',
    role: 'Automation System Assistant',
    companyLabel: 'Umpo',
    companyFullName: 'Universitas Muhammadiyah Ponorogo',
    address: 'Ponorogo, Indonesia 🇮🇩',
    fromDate: new Date('2022-11-01'),
    endDate: new Date('2024-07-01'),
    workMode: 'Part-time',
    workType: 'Hybrid',
    responsibilities: [
      'Assisting instructor at teaching the students with Automation System subject.',
      'Scoring all the exams and the tasks that the instructor gives to students',
      'Monitoring student\'s demo projects.',
    ],
  },
  {
    logoUrl: '/images/ate.jpeg',
    role: 'Frontend Web Developer',
    companyLabel: 'ATE',
    companyFullName: 'PT. Aceh Technology Enthusiast',
    address: 'Banda Aceh, Indonesia 🇮🇩',
    fromDate: new Date('2021-12-01'),
    endDate: new Date('2023-01-01'),
    workMode: 'Part-time',
    workType: 'Hybrid',
    responsibilities: [
      'Refactored the HTML, CSS, and JavaScript code of existing web pages to improve page loading speed.',
      'Implemented a user login system to allow for security and authentication.',
      'Used cross-browser compatibility techniques to ensure pages render the same across all browsers.',
      'Designed and built a new responsive website frontend layout.',
      'Developed custom JavaScript widgets to enhance UX.',
    ],
  },
  {
    logoUrl: '/svgs/maven.webp',
    role: 'Backend Engineer',
    companyLabel: 'Maven Digital Asia',
    companyFullName: 'Maven Digital Asia',
    address: 'Jakarta Barat,, Indonesia 🇮🇩',
    fromDate: new Date('2023-01-01'),
    endDate: new Date('2024-04-01'),
    workMode: 'Full-time',
    workType: 'Remote',
    responsibilities: [
      'Designed multiple websites utilizing HTML, CSS, JavaScript, and Typescript.',
      'Developed components and repackaged existing components for reuse using Typescript.',
      'Debugged and maintained websites with cross-browser compatibility issues.',
      'Debugged and maintained React Native project with cross-platform compatibility issues.',
      'Developed modern front-end user interfaces with ReactJS and React Native.',
      'Collaborated with back-end developers to implement RESTful API endpoints.',
      'Sometimes collaborated with the architect team to set up the deployment server.',
    ],
  },
  {
    logoUrl: '/images/machine-vision.png',
    role: 'Frontend Developer',
    companyLabel: 'Machine Vision',
    companyFullName: 'PT. Lanius Inovasi Indonesia',
    address: 'Malang, Indonesia 🇮🇩',
    fromDate: new Date('2024-01-01'),
    endDate: new Date('2024-05-01'),
    workMode: 'Freelance',
    workType: 'Remote',
    responsibilities: [
      'Build reusable code and libraries for future use.',
      'Ensure the technical feasibility of UI/UX designs.',
      'Revamp several existing components using ReactJS and Material UI.',
      'Bug fixing.',
    ],
  },
  {
    logoUrl: '/svgs/xcidic.svg',
    role: 'Frontend Developer',
    companyLabel: 'Xcidic',
    companyFullName: 'PT. Xcidic Teknologi Indonesia',
    address: 'Jakarta, Indonesia 🇮🇩',
    fromDate: new Date('2024-04-01'),
    workMode: 'Full-time',
    workType: 'Remote',
    responsibilities: [
      'Build internal project components template.',
      'Worked on a new version of a freelancer marketplace web application (sribu.com). As a frontend developer, I personally worked on the dashboard layout, header, sidebar, footer, and implemented best practice to enhance performance and SEO.',
      'Slicing UI with pixel perfect.',
      'Team working with agile development method.',
      'Problem solving and bug fixing.',
    ],
  },
];
